name: bot-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - beautifulsoup4
  - numpy>=1.20.3
  - pandas>=1.3.0
  - scikit-learn=0.24.2
  - nltk>=3.5
  - pyspellchecker
  - python-telegram-bot
  - requests
  - lxml
  #- pip>=21.2.0
  #- pip:
  #    lxml
